spring:
  quartz:
    job-store-type: jdbc
    
    jdbc:
      #    initialize-schema: never
      initialize-schema: always
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          
#          jobs:
#            simpleJob: #Config simple job
#              jobClass: com.colak.springtutorial.job.MyJob
#              cron: "*/10 * * * * ?"
          
          scheduler:
            # This gives a name to the Quartz scheduler instance, which can help in identifying it in logs or management interfaces.
            instanceName: QuartzScheduler
            #  The AUTO value indicates that Quartz should automatically generate an instance ID.
            instanceId: AUTO
            
          jobStore:
            # When set to true, this tells Quartz to use the configuration properties defined in this YAML file.
            useProperties: true
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            # When set to true, it enables clustering. In a clustered setup, multiple instances of the application can share the same job store,
            # ensuring that only one instance executes a job at a time. This is crucial in distributed systems to avoid duplicate job execution.
            isClustered: true

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  